###############################################################################
#
# DOCKER COMPOSE - MEDIA-CENTER BY JUFTIN
#
###############################################################################

version:                    "3.6"

###############################################################################
# SERVICES CONFIGURATION
###############################################################################

services:

###############################################################################
# FRONTEND SERVICES
###############################################################################

#############################
# PORTAINER CONFIGURATION
#############################
  portainer:
    container_name:         portainer
    hostname:               portainer
    image:                  portainer/portainer:latest
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_DIR}/portainer/config:/data
      - ${DOCKER_DIR}/shared:/shared
    ports:
      - 9000:9000
      - 8000:8000
    command:                -H unix:///var/run/docker.sock
    labels:
      com.ouroboros.enable: "true"
    restart:                unless-stopped
    networks:
      bridge:
        ipv4_address:       172.16.238.11

#############################
# ORGANIZR CONFIGURATION
#############################

  organizr:
    container_name:         organizr
    image:                  lsiocommunity/organizr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/organizr:/config
      - ${DOCKER_DIR}/shared:/shared
    ports:
      - 80:80
    restart:                unless-stopped
    networks:
      bridge:
        ipv4_address:       172.16.238.12

###############################################################################
# DOCKER MAINTENANCE
###############################################################################

#############################
# OUROBOROS CONFIGURATION
#############################
  ouroboros:
    container_name:         ouroboros
    hostname:               ouroboros
    image:                  pyouroboros/ouroboros:latest
    environment:
      - INTERVAL=1800
      - CLEANUP=True
      - LABEL_ENABLE=TRUE
      - LABELS_ONLY=True
      - SELF_UPDATE=True
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart:                unless-stopped
    networks:
      bridge:
        ipv4_address:       172.16.238.13

###############################################################################
# DOWNLOAD CLIENTS
###############################################################################

#############################
# TRASNMISSION CONFIGURATION
#############################

  transmission:
    container_name:         transmission
    hostname:               transmission
    image:                  haugene/transmission-openvpn:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - TRANSMISSION_IDLE_SEEDING_LIMIT=0
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=True
      - TRANSMISSION_WEB_UI=combustion
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/transmission/config:/data/transmission-home
      - ${DOCKER_DIR}/transmission/watch:/data/watch
      - ${COMPLETED_DOWNLOADS}:/downloads
      - ${INCOMPLETE_DOWNLOADS}:/data/incomplete
      - ${DOCKER_DIR}/shared:/shared
    ports:
      - 9091:9091
    dns:
      - 8.8.8.8
      - 8.8.4.4
    labels:
      com.ouroboros.enable: "true"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart:                unless-stopped
    networks:
      bridge:
        ipv4_address:       172.16.238.14

###############################################################################
# PERSONAL VIDEO RECORDERS
###############################################################################

#############################
# RADARR CONFIGURATION
#############################

  radarr:
    image:                  linuxserver/radarr:latest
    hostname:               radarr
    container_name:         radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/radarr/config:/config
      - ${COMPLETED_DOWNLOADS}:/downloads
      - ${MOVIE_DIR}:/movies
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/shared:/shared
    ports:
      - 7878:7878
    labels:
      com.ouroboros.enable: "true"
    restart:                unless-stopped
    networks:
      bridge:
        ipv4_address:       172.16.238.15

#############################
# SONARR CONFIGURATION
#############################

  sonarr:
    image:                  linuxserver/sonarr:latest
    hostname:               sonarr
    container_name:         sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/sonarr/config:/config
      - ${COMPLETED_DOWNLOADS}:/downloads
      - ${TV_DIR}:/tv
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/shared:/shared
    ports:
      - 8989:8989
    labels:
      com.ouroboros.enable: "true"
    restart:                unless-stopped
    networks:
      bridge:
        ipv4_address:       172.16.238.16

###############################################################################
# MEDIA SERVER APPS
###############################################################################

#############################
# PLEX CONFIGURATION
#############################

  plex:
    container_name:         plex
    hostname:               plex
    image:                  linuxserver/plex:latest
    network_mode:           host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_DIR}/plex/config:/config
      - ${TRANSCODE_DIR}:/transcode
      - ${TV_DIR}:/tv
      - ${MOVIE_DIR}:/movies
      - ${DOCKER_DIR}/shared:/shared
    labels:
      com.ouroboros.enable: "true"
    restart:                unless-stopped

#############################
# TAUTULLI CONFIGURATION
#############################

  tautulli:
    container_name:         tautulli
    hostname:               tautulli
    image:                  linuxserver/tautulli:latest
    volumes:
      - ${DOCKER_DIR}/tautulli/config:/config
      - ${DOCKER_DIR}/tautulli/logs:/logs:ro
      - ${DOCKER_DIR}/shared:/shared
    ports:
      - 8181:8181
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      com.ouroboros.enable: "true"
    restart:                unless-stopped
    networks:
      bridge:
        ipv4_address:       172.16.238.17

#############################
# OMBI CONFIGURATION
#############################

  ombi:
    container_name:         ombi
    image:                  linuxserver/ombi:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/ombi/config:/config
      - ${DOCKER_DIR}/shared:/shared
    ports:
      - 3579:3579
    labels:
      com.ouroboros.enable: "true"
    restart:                unless-stopped
    networks:
      bridge:
        ipv4_address:       172.16.238.18

###############################################################################
# SEARCHER / INDEXER APPS
###############################################################################

#############################
# JACKETT CONFIGURATION
#############################

  jackett:
    container_name:         jackett
    hostname:               jackett
    image:                  linuxserver/jackett:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/jackett/config:/config
      - ${COMPLETED_DOWNLOADS}:/downloads
      - "/etc/localtime:/etc/localtime:ro"
      - ${DOCKER_DIR}/shared:/shared
    ports:
      - 9117:9117
    labels:
      com.ouroboros.enable: "true"
    restart:                unless-stopped
    networks:
      bridge:
        ipv4_address:       172.16.238.19

###############################################################################
# UTILITIES
###############################################################################

#############################
# SAMBA CONFIGURATION
#############################

  samba:
    container_name:         samba
    hostname:               samba
    image:                  dperson/samba:latest
    environment:
      - USERID=${PUID}
      - GROUPID=${PGID}
      - WORKGROUP=workgroup
      - "SHARE=NAS;/mount;yes;no;yes;all;none;;NAS;"
      - "SHARE2=juftin;/mount2;yes;no;yes;all;none;;juftin;"
      - TZ=MST7MDT
    volumes:
      - /media/juftin/NAS:/mount
      - /home/juftin:/mount2/
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    labels:
      com.ouroboros.enable: "true"
    restart:                unless-stopped
    networks:
      bridge:
        ipv4_address:       172.16.238.20

#############################
#  NO-IP CONFIGURATION
#############################

  # no-ip:
  #   image:                coppit/no-ip:latest
  #   container_name:       no-ip
  #   # environment:
  #   #   - USERNAME=${NO_IP_USER}
  #   #   - PASSWORD=${NO_IP_PASSWORD}
  #   #   - DOMAINS=${NO_IP_DOMAIN}
  #   #   - INTERVAL=5m
  #   volumes:
  #     - ${DOCKER_DIR}/no-ip/config:/config
  #     - /etc/localtime:/etc/localtime:ro
  #   labels:
  #     com.ouroboros.enable: "true"
  #   privileged:           "true"
  #   restart:              unless-stopped

###############################################################################
# NETWORKING CONFIGURATION
###############################################################################

networks:
  bridge:
    driver:                 bridge
    ipam:
      driver:               default
      config:
      - subnet:             172.16.238.0/24
