###############################################################################
#
# DOCKER COMPOSE - MEDIA-CENTER BY JUFTIN
#
###############################################################################

version:                                                 "3.7"

###############################################################################
# SERVICES CONFIGURATION
###############################################################################

services:

###############################################################################
# NETWORKING SERVICES
###############################################################################

#############################
# TRAEFIK CONFIGURATION
#############################

  traefik:
    container_name:                                      traefik
    hostname:                                            traefik
    image:                                               traefik:v1.7.16
    domainname:                                          ${DOMAINNAME}
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_DIR}/traefik/config:/etc/traefik
      - ${DOCKER_DIR}/shared:/shared
    restart:                                             unless-stopped
    networks:
      - default
      - traefik_proxy
    labels:
      com.ouroboros.enable:                              true
      traefik.enable:                                    true
      traefik.backend:                                   traefik
      traefik.protocol:                                  http
      traefik.port:                                      8080
      traefik.frontend.rule:                             Host:traefik.${DOMAINNAME}
      traefik.frontend.headers.SSLHost:                  traefik.${DOMAINNAME}
      traefik.docker.network:                            traefik_proxy
      traefik.frontend.passHostHeader:                   true
      traefik.frontend.headers.SSLForceHost:             true
      traefik.frontend.headers.SSLRedirect:              true
      traefik.frontend.headers.browserXSSFilter:         true
      traefik.frontend.headers.contentTypeNosniff:       true
      traefik.frontend.headers.forceSTSHeader:           true
      traefik.frontend.headers.STSSeconds:               315360000
      traefik.frontend.headers.STSIncludeSubdomains:     true
      traefik.frontend.headers.STSPreload:               true
      traefik.frontend.headers.customResponseHeaders:    X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny:                true
      traefik.frontend.headers.customFrameOptionsValue:  'allow-from https:${DOMAINNAME}'
      traefik.frontend.auth.forward.address:             "http://oauth:4181"
      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
      traefik.frontend.auth.forward.trustForwardHeader:  true

#############################
# OAUTH CONFIGURATION
#############################

  oauth:
    image:                                               thomseddon/traefik-forward-auth:latest
    container_name:                                      oauth
    hostname:                                            oauth
    restart:                                             unless-stopped
    networks:
      - default
      - traefik_proxy
    environment:
      PROVIDERS_GOOGLE_CLIENT_ID:                        ${GOOGLE_CLIENT_ID}
      PROVIDERS_GOOGLE_CLIENT_SECRET:                    ${GOOGLE_CLIENT_SECRET}
      SECRET:                                            ${OAUTH_SECRET}
      COOKIE_DOMAIN:                                     ${DOMAINNAME}
      INSECURE_COOKIE:                                   "false"
      AUTH_HOST:                                         oauth.${DOMAINNAME}
      URL_PATH:                                          /_oauth
      WHITELIST:                                         ${OAUTH_WHITELIST}
      LOG_LEVEL:                                         info
      LIFETIME:                                          2592000 # 30 DAYS
    labels:
      com.ouroboros.enable:                              true
      traefik.enable:                                    true
      traefik.backend:                                   oauth
      traefik.port:                                      4181
      traefik.frontend.rule:                             Host:oauth.${DOMAINNAME}
      traefik.frontend.headers.SSLHost:                  oauth.${DOMAINNAME}
      traefik.docker.network:                            traefik_proxy
      traefik.frontend.passHostHeader:                   true
      traefik.frontend.headers.SSLForceHost:             true
      traefik.frontend.headers.customResponseHeaders:    X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.SSLRedirect:              true
      traefik.frontend.headers.browserXSSFilter:         true
      traefik.frontend.headers.contentTypeNosniff:       true
      traefik.frontend.headers.forceSTSHeader:           true
      traefik.frontend.headers.STSSeconds:               315360000
      traefik.frontend.headers.STSIncludeSubdomains:     true
      traefik.frontend.headers.STSPreload:               true
      traefik.frontend.headers.frameDeny:                true
      traefik.frontend.auth.forward.address:             "http://oauth:4181"
      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
      traefik.frontend.auth.forward.trustForwardHeader:  true

###############################################################################
# FRONTEND SERVICES
###############################################################################

#############################
# PORTAINER CONFIGURATION
#############################

  portainer:
    container_name:                                      portainer
    # hostname:                                          portainer
    image:                                               portainer/portainer:latest
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_DIR}/portainer/config:/data
      - ${DOCKER_DIR}/shared:/shared
    command:                                             -H unix:///var/run/docker.sock
    restart:                                             unless-stopped
    networks:
      - traefik_proxy
    labels:
      com.ouroboros.enable:                              true
      traefik.enable:                                    true
      traefik.backend:                                   portainer
      traefik.protocol:                                  http
      traefik.port:                                      9000
      traefik.frontend.rule:                             Host:portainer.${DOMAINNAME}
      traefik.frontend.headers.SSLHost:                  portainer.${DOMAINNAME}
      traefik.docker.network:                            traefik_proxy
      traefik.frontend.passHostHeader:                   true
      traefik.frontend.headers.SSLForceHost:             true
      traefik.frontend.headers.SSLRedirect:              true
      traefik.frontend.headers.browserXSSFilter:         true
      traefik.frontend.headers.contentTypeNosniff:       true
      traefik.frontend.headers.forceSTSHeader:           true
      traefik.frontend.headers.STSSeconds:               315360000
      traefik.frontend.headers.STSIncludeSubdomains:     true
      traefik.frontend.headers.STSPreload:               true
      traefik.frontend.headers.customResponseHeaders:    X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny:                true
      traefik.frontend.headers.customFrameOptionsValue:  'allow-from https:${DOMAINNAME}'
      traefik.frontend.auth.forward.address:             "http://oauth:4181"
      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
      traefik.frontend.auth.forward.trustForwardHeader:  true

###############################################################################
# DOCKER MAINTENANCE
###############################################################################

#############################
# OUROBOROS CONFIGURATION
#############################
  ouroboros:
    container_name:                                      ouroboros
    hostname:                                            ouroboros
    image:                                               pyouroboros/ouroboros:latest
    environment:
      - INTERVAL=1800
      - CLEANUP=True
      - LABEL_ENABLE=TRUE
      - LABELS_ONLY=True
      - SELF_UPDATE=True
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart:                                             unless-stopped
    networks:
      - default

###############################################################################
# DOWNLOAD CLIENTS
###############################################################################

#############################
# TRASNMISSION CONFIGURATION
#############################

  transmission:
    container_name:                                      transmission
    hostname:                                            transmission
    image:                                               haugene/transmission-openvpn:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - TRANSMISSION_IDLE_SEEDING_LIMIT=0
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=True
      - TRANSMISSION_WEB_UI=combustion
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      # - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      # - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      # - TRANSMISSION_RPC_USERNAME={DOCKER_USER_NAME}
      # - TRANSMISSION_RPC_PASSWORD={DOCKER_PASSWORD}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/transmission/config:/data/transmission-home
      - ${DOCKER_DIR}/transmission/watch:/data/watch
      - ${COMPLETED_DOWNLOADS}:/downloads
      - ${INCOMPLETE_DOWNLOADS}:/data/incomplete
      - ${DOCKER_DIR}/shared:/shared
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart:                                             unless-stopped
    networks:
      - traefik_proxy
    ports:
       - 9091:9091
    labels:
      com.ouroboros.enable:                              true
      traefik.enable:                                    true
      traefik.backend:                                   transmission
      traefik.protocol:                                  http
      traefik.port:                                      9091
      traefik.frontend.rule:                             Host:transmission.${DOMAINNAME}
      traefik.frontend.headers.SSLHost:                  transmission.${DOMAINNAME}
      traefik.docker.network:                            traefik_proxy
      traefik.frontend.passHostHeader:                   true
      traefik.frontend.headers.SSLForceHost:             true
      traefik.frontend.headers.SSLRedirect:              true
      traefik.frontend.headers.browserXSSFilter:         true
      traefik.frontend.headers.contentTypeNosniff:       true
      traefik.frontend.headers.forceSTSHeader:           true
      traefik.frontend.headers.STSSeconds:               315360000
      traefik.frontend.headers.STSIncludeSubdomains:     true
      traefik.frontend.headers.STSPreload:               true
      traefik.frontend.headers.customResponseHeaders:    X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny:                true
      traefik.frontend.headers.customFrameOptionsValue:  'allow-from https:${DOMAINNAME}'
      traefik.frontend.auth.forward.address:             "http://oauth:4181"
      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
      traefik.frontend.auth.forward.trustForwardHeader:  true

#############################
# OMBI CONFIGURATION
#############################

  ombi:
    container_name:                                      ombi
    image:                                               linuxserver/ombi:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/ombi/config:/config
      - ${DOCKER_DIR}/shared:/shared
    restart:                                             unless-stopped
    networks:
      - traefik_proxy
    labels:
      traefik.enable:                                    true
      traefik.backend:                                   ombi
      traefik.protocol:                                  http
      traefik.port:                                      3579
      traefik.frontend.rule:                             Host:ombi.${DOMAINNAME}
      traefik.frontend.headers.SSLHost:                  ombi.${DOMAINNAME}
      traefik.docker.network:                            traefik_proxy
      traefik.frontend.passHostHeader:                   true
      traefik.frontend.headers.SSLForceHost:             true
      traefik.frontend.headers.SSLRedirect:              true
      traefik.frontend.headers.browserXSSFilter:         true
      traefik.frontend.headers.contentTypeNosniff:       true
      traefik.frontend.headers.forceSTSHeader:           true
      traefik.frontend.headers.STSSeconds:               315360000
      traefik.frontend.headers.STSIncludeSubdomains:     true
      traefik.frontend.headers.STSPreload:               true
      traefik.frontend.headers.customResponseHeaders:    X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny:                true
      traefik.frontend.headers.customFrameOptionsValue:  'allow-from https:${DOMAINNAME}'
      traefik.frontend.auth.forward.address:             "http://oauth:4181"
      traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
      traefik.frontend.auth.forward.trustForwardHeader:  true

###############################################################################
# NETWORKING CONFIGURATION
###############################################################################

networks:
  traefik_proxy:
    external:
      name:                                              traefik_proxy
  default:
    driver:                                              bridge
