###############################################################################
#
# DOCKER COMPOSE - MEDIA-CENTER BY JUFTIN
#
###############################################################################

version:                                             "3.7"

###############################################################################
# SERVICES CONFIGURATION
###############################################################################

services:

###############################################################################
# NETWORKING SERVICES
###############################################################################

#############################
# TRAEFIK CONFIGURATION
#############################

  traefik:
    container_name:                                  traefik
    hostname:                                        traefik
    image:                                           traefik:v1.7.16
    domainname:                                      ${DOMAINNAME}
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_DIR}/traefik/config:/etc/traefik
      - ${DOCKER_DIR}/shared:/shared
    restart:                                         unless-stopped
    networks:
      - default
      - traefik_proxy
    labels:
      traefik.enable:                                true
      traefik.backend:                               traefik
      traefik.frontend.rule:                         Host:traefik.${DOMAINNAME}
      traefik.port:                                  8080
      traefik.docker.network:                        traefik_proxy
      ttraefik.frontend.headers.SSLRedirect:         true
      traefik.frontend.headers.STSSeconds:           315360000
      traefik.frontend.headers.browserXSSFilter:     true
      traefik.frontend.headers.contentTypeNosniff:   true
      traefik.frontend.headers.forceSTSHeader:       true
      traefik.frontend.headers.SSLHost:              juftin.com
      traefik.frontend.headers.STSIncludeSubdomains: true
      traefik.frontend.headers.STSPreload:           true
      traefik.frontend.headers.frameDeny:            true
      traefik.frontend.auth.basic.users:             ${HTTP_USERNAME}:${HTTP_PASSWORD}

###############################################################################
# NETWORKING CONFIGURATION
###############################################################################

networks:
  traefik_proxy:
    external:
      name:                                          traefik_proxy
  default:
    driver:                                          bridge
